### ISSUE TITLE
Datatables plugin not working due to almasaeed2010/adminlte update

### ISSUE THREAD

**Issue by andreafiori** [yiister/yii2-adminlte#6]
Hello,

datatables plugin has been removed from almasaeed2010/adminlte latest versions and now the admin area is not working.
I have to replace the almasaeed2010 with an older version manually otherwise the GridView is not able to load the @vendor/almasaeed2010/adminlte/plugins/datatables sourcepath. I don't know what happened and if I have update some dependencies.

Best,

Andrea

**Comment by fps01** [comment]
@andreafiori Thanks for bug report. I'll fix it in feature.

**Comment by khvalov** [comment]
It will be nice to update GridViewAsset.php string to new path as well:
`public $sourcePath = '@vendor/bower-asset/datatables';`
